name: Greetings

on: [pull_request, issues, push]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      deployments: write
    steps:
    - uses: Hofmanninger-Florian/3CAndroidProjekt@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'U did it my boy, i am proud of u'
        pr-message: 'Pull that it come on, yes u did it!'
        push-message: 'Yes we did the push my friend'
